### PR TITLE
global refactor "Michalis" --> "Michaelis"

### PR DESCRIPTION
**Pull request by eldad-a**
This is to address #99 , and upon @zoltuz 's request.

**NB** I am not aware of any tests, so non were ran; moreover, my familiarity with this package is limited to the [SBtools June2020 bootcamp](https://www.cds.caltech.edu/~murray/wiki/SBtools_Bootcamp,_June_2020). Therefore, be as suspicious as possible -- things could be broken badly... :-) . 

I ran:
```sed -i 's/Michalis/Michaelis/g' ./biocrnpyler/*``` 
and
```sed -i 's/Michalis/Michaelis/g' ./examples/Parameters\ loading.ipynb```

Verified using:
```grep -rnw './' -e 'Michalis'```
That all strings have been replaced.

Hope that was not too foolish...

### CODE REVIEW

**Comment by eldad-a** [comment]
Two comments:

1. Any code relying on `MichalisMenten*` , that is, before typo correction, would be broken by this refactoring. One way to avoid this is to include an alias  `MichalisMenten* = `MichaelisMenten*` ; and include a future deperication warning.

2. I've re-run the `ipynb`s from today's bootcamp, replacing `MichalisMenten` for `MichaelisMenten`, and all ran well. This is obviously not a complete test, yet an positive indication.

**Comment by zoltuz** [comment]
Thanks for your contribution! There are some hoops to jump, but bear with me! Fist, please rebase your branch to dev, so you get the latest updates: 
```
git fetch upstream/dev
git checkout refactor_Michaelis
git rebase upstream/dev
```
Once you have that you need to force push:
```
git push -f
```
After that, we can see whether Travis can check/build your code.

**Comment by eldad-a** [comment]
Sure, my pleasure!

Thanks for the detailed instructions.
Here's an error I receive:

```bash
$ git fetch upstream/dev

fatal: 'upstream/dev' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
```bash
$ git config --get remote.origin.url

https://github.com/eldad-a/BioCRNPyler.git
```

When you have a minute, I'd appreciate your advice.

**Comment by zoltuz** [comment]
Sure! Please have a look here: https://github.com/BuildACell/BioCRNPyler/wiki/how-to-sync-your-BioCRNPyler-fork
you should see something like this when upstream is correctly configured:
```
➜ git remote --verbose
origin  git@github.com:zoltuz/biocrnpyler.git (fetch)
origin  git@github.com:zoltuz/biocrnpyler.git (push)
upstream        git@github.com:BuildACell/BioCRNPyler.git (fetch)
upstream        git@github.com:BuildACell/BioCRNPyler.git (push)

```

**Comment by eldad-a** [comment]
To me it seems similar, what am I missing?

```
$ git remote --verbose
origin	https://github.com/eldad-a/BioCRNPyler.git (fetch)
origin	https://github.com/eldad-a/BioCRNPyler.git (push)
upstream	https://github.com/BuildACell/BioCRNPyler.git (fetch)
upstream	https://github.com/BuildACell/BioCRNPyler.git (push)
```

**Comment by zoltuz** [comment]
no idea, try this then
```
git fetch -all
git checkout dev
git merge
git checkout refactor_Michaelis
git rebase dev
```

**Comment by eldad-a** [comment]
Thanks!

Let's hope for the best :-)

Including the outputs for reference

```
$ git fetch --all
Fetching origin
From https://github.com/eldad-a/BioCRNPyler
   e9289a9..c165e88  master     -> origin/master
Fetching upstream

$ git checkout dev
Branch 'dev' set up to track remote branch 'dev' from 'upstream'.
Switched to a new branch 'dev'

$ git merge
Already up to date.

$ git checkout refactor_Michaelis
Switched to branch 'refactor_Michaelis'
Your branch is up to date with 'origin/refactor_Michaelis'.

$ git rebase dev
First, rewinding head to replay your work on top of it...
Applying: global refactor "Michalis" --> "Michaelis"
Using index info to reconstruct a base tree...
A	examples/Developer Overview.ipynb
A	examples/Parameters loading.ipynb
Falling back to patching base and 3-way merge...
Auto-merging examples/8. Developer Overview.ipynb
Auto-merging examples/5. Parameters.ipynb

$ git push -f
Username for 'https://github.com': eldad-a
Password for 'https://eldad-a@github.com': 
Counting objects: 12, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (7/7), done.
Writing objects: 100% (12/12), 1.17 KiB | 1.17 MiB/s, done.
Total 12 (delta 11), reused 5 (delta 5)
remote: Resolving deltas: 100% (11/11), completed with 11 local objects.
To https://github.com/eldad-a/BioCRNPyler.git
 + 4083ea6...427ebfa refactor_Michaelis -> refactor_Michaelis (forced update)

```

**Comment by zoltuz** [comment]
All green! Thanks for your contribution!

**Comment by eldad-a** [comment]
> All green! Thanks for your contribution!

Following your directions made it effortless  :-)
Thank you!

**Comment by eldad-a** [comment]
> no idea, try this then
> 
> ...

May be worth including :
```
git fetch upstream dev
git checkout <branch_with_amazing_new_feature>
git rebase upstream/dev
git push origin <branch_with_amazing_new_feature>
```

In [how-to-sync-your-BioCRNPyler-fork](https://github.com/BuildACell/BioCRNPyler/wiki/how-to-sync-your-BioCRNPyler-fork)
for future PRs.

NB `git fetch upstream dev` without `/`, while `git rebase upstream/dev` with.

**Pull request merged**
