### PR TITLE
Minor sbml fixes

### PR DESCRIPTION
**Pull request by ayush9pandey**
* Added sbml_warnings keyword argument to simulate with bioscrape functions

Working pull request, not yet ready to merge. Need to check if everything works smoothly or not.

### CODE REVIEW

**Comment by WilliamIX** [comment]
@ayush9pandey are you ready for this to be merged?

**Comment by ayush9pandey** [comment]
OK, now this pull request is ready to merge.

**Comment by ayush9pandey** [comment]
The Travis CI check is passing - so the tests are passing I assume. For some reason codecov/patch is giving an error but it doesn't seem like there are any details there. Any ideas @zoltuz ?

**Comment by zoltuz** [comment]
No idea, as long as Travis CI builds the package and test it, we are generally good to go. (The code coverage report is generated __after__ the CI build, so if we get a codecov report, then the PR surely works. )

**Comment by WilliamIX** [comment]
Having a similar issue with my newest merge - travis fails on github, but when I run python setup.py test everything passes on my local machine.

**Comment by zoltuz** [comment]
It's an issue with your latest example (I'm sure it's bioscrape related, that's why it works on your local maschine)
Screenshot 2020-06-16 at 16 52 58

**Comment by murrayrm** [comment]
Regarding Travis versus local testing: this could be a problem with various versions of packages that are installed.  If you create a new condo environment and walk through the steps in the `.travis.yml` file, you should be able to recreate the error locally.

**Comment by zoltuz** [comment]
Yep, Richard's solution a good way to drive out the package differences.

This is what I suggested to Matthieu yesterday with his PR #89 : 

1, create a new virtual environment https://realpython.com/lessons/creating-virtual-environment/
2, activate your virtual env
3, check out your github code in the PR with git clone
4, run 
```terminal
python setup.py test 
```

**Comment by WilliamIX** [comment]
I saw that exchange - having to switch environments all the time for testing is a pain, and will also add to the barrier of entry for new contributors. Do you think it is possible to put something in CRN.simulate_with_bioscrape(...) and CRN.simulate_with_bioscrape_via_sbml(...) like try and catch statements so we don't get errors if bioscrape is not installed? This will ensure that all of our examples work, without forcing people to do fancy try and catch statements themselves.

**Pull request merged**
