### PR TITLE
Support old dnaplotlib

### PR DESCRIPTION
**Pull request by dr3y**
should be fix to issue #156 

and also uncommented some commented out plotNetwork() lines in DNA_construct examples

### CODE REVIEW

**Comment by zoltuz** [comment]
I couldn't make the ```plotNetwork()``` work without the plotting package, so good luck getting it through Travis

**Comment by zoltuz** [comment]
There're 18 commits (which are actually really old commits), but no files have changed it to go to the Files changed tab.

**Comment by dr3y** [comment]
I don't know why there are so many commits

**Comment by ayush9pandey** [comment]
Travis is passing. I am merging this (will squash all the comments)

**Pull request merged**
