### PR TITLE
Feature Sphinx generated documentation

### LINKED ISSUE #169: setup Sphinx to generate the documentation
Hi all, 

Here's a suggestion, I'm not super familiar with Sphinx (I never got it to work actually), so I was thinking about an alternative software to automatically generate the documentation. One suggestion would be MkDocs, which works with plain markdown files:
https://www.mkdocs.org/
There's a plug that can generate the documentation from the source code:
https://github.com/pawamoy/mkdocstrings

Let me know what you think!

### PR DESCRIPTION
**Pull request by zoltuz**
Please do **not** squash the commits in this PR!

- autogenerated docs with Sphinx
- automatic Jupyter notebook to HTML conversion
- makefile to run the whole toolchain
- autogenerated API documentation using docstrings

closes #169

### CODE REVIEW

**Comment by WilliamIX** [comment]
I think this looks good - how do I look at the generated documentation to test it?

**Comment by zoltuz** [comment]
> I think this looks good - how do I look at the generated documentation to test it?

Great question, I forgot to write it down. Here's a wiki page for that:
https://github.com/BuildACell/BioCRNPyler/wiki/How-to-generate-the-documentation-on-your-local-mashine

Let me know if you have questions.

**Comment by WilliamIX** [comment]
> > I think this looks good - how do I look at the generated documentation to test it?
> 
> Great question! I forgot to write it down. Here's a wiki page for that:
> https://github.com/BuildACell/BioCRNPyler/wiki/How-to-generate-the-documentation-on-your-local-mashine
> 
> Let me know if you have questions.



> > I think this looks good - how do I look at the generated documentation to test it?
> 
> Great question! I forgot to write it down. Here's a wiki page for that:
> https://github.com/BuildACell/BioCRNPyler/wiki/How-to-generate-the-documentation-on-your-local-mashine
> 
> Let me know if you have questions.

I cannot get either of these to work on Windows.

Option A breaks here:

`(base) C:\Users\wp_ix\OneDrive\Caltech\Code\BioCRNPyler\docs>make docs
Running Sphinx v3.4.0

Sphinx error:
Builder name docs not registered or available through entry point`

Option B breaks here:

`(base) C:\Users\wp_ix\OneDrive\Caltech\Code\BioCRNPyler\docs>python generate_nblinks.py
Traceback (most recent call last):
  File "generate_nblinks.py", line 47, in <module>
    main()
  File "generate_nblinks.py", line 36, in main
    with open(f"source/examples/{one_nb.stem}.nblink", "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'source/examples/1. Building CRNs Directly.nblink'`

**Comment by zoltuz** [comment]
> https://github.com/BuildACell/BioCRNPyler/wiki/How-to-generate-the-documentation-on-your-local-mashine

to make option A work, you need to be here:
C:\Users\wp_ix\OneDrive\Caltech\Code\BioCRNPyler>make docs


I'm looking into Option B. If I understand correctly: `python generate_nblinks.py` step breaks.

**Comment by zoltuz** [comment]
@WilliamIX , I've added the missing example directory. Please pull the latest commit and try it again. Sorry for the trouble!

**Comment by WilliamIX** [comment]
> @WilliamIX , I've added the missing example directory. Please pull the latest commit and try it again. Sorry for the trouble!

Something is still not working:

(base) C:\Users\wp_ix\OneDrive\Caltech\Code\BioCRNPyler>cd docs

Option A:
(base) C:\Users\wp_ix\OneDrive\Caltech\Code\BioCRNPyler\docs>make docs
Running Sphinx v3.4.0

Sphinx error:
Builder name docs not registered or available through entry point

Option B:

(base) C:\Users\wp_ix\OneDrive\Caltech\Code\BioCRNPyler\docs>sphinx-apidoc -o source/ ../biocrnpyler
Creating file source/biocrnpyler.rst.
Creating file source/modules.rst.

(base) C:\Users\wp_ix\OneDrive\Caltech\Code\BioCRNPyler\docs>python generate_nblinks.py
Creating path for ..\examples\1. Building CRNs Directly.ipynb
Creating path for ..\examples\2. Compiling CRNs with Enzymes Catalysis and Binding.ipynb
Creating path for ..\examples\5. Parameters.ipynb
Creating path for ..\examples\6. Global Mechanisms.ipynb
Creating path for ..\examples\7. Network Plotting Examples.ipynb
Creating path for ..\examples\8. Developer Overview.ipynb
Creating path for ..\examples\DNA_construct Examples.ipynb
Creating path for ..\examples\roadrunner_example.ipynb
Creating nb_examples.rst

(base) C:\Users\wp_ix\OneDrive\Caltech\Code\BioCRNPyler\docs>make.bat clean

(base) C:\Users\wp_ix\OneDrive\Caltech\Code\BioCRNPyler\docs>make.bat HTML
Running Sphinx v3.4.0

Sphinx error:
Builder name HTML not registered or available through entry point

**Comment by zoltuz** [comment]
> > @WilliamIX , I've added the missing example directory. Please pull the latest commit and try it again. Sorry for the trouble!
> 
> Something is still not working:
> 
> (base) C:\Users\wp_ix\OneDrive\Caltech\Code\BioCRNPyler>cd docs
> 
> Option A:
> (base) C:\Users\wp_ix\OneDrive\Caltech\Code\BioCRNPyler\docs>make docs
> Running Sphinx v3.4.0
> 
> Sphinx error:
> Builder name docs not registered or available through entry point
> 
> Option B:
> 
> (base) C:\Users\wp_ix\OneDrive\Caltech\Code\BioCRNPyler\docs>sphinx-apidoc -o source/ ../biocrnpyler
> Creating file source/biocrnpyler.rst.
> Creating file source/modules.rst.
> 
> (base) C:\Users\wp_ix\OneDrive\Caltech\Code\BioCRNPyler\docs>python generate_nblinks.py
> Creating path for ..\examples\1. Building CRNs Directly.ipynb
> Creating path for ..\examples\2. Compiling CRNs with Enzymes Catalysis and Binding.ipynb
> Creating path for ..\examples\5. Parameters.ipynb
> Creating path for ..\examples\6. Global Mechanisms.ipynb
> Creating path for ..\examples\7. Network Plotting Examples.ipynb
> Creating path for ..\examples\8. Developer Overview.ipynb
> Creating path for ..\examples\DNA_construct Examples.ipynb
> Creating path for ..\examples\roadrunner_example.ipynb
> Creating nb_examples.rst
> 
> (base) C:\Users\wp_ix\OneDrive\Caltech\Code\BioCRNPyler\docs>make.bat clean
> 
> (base) C:\Users\wp_ix\OneDrive\Caltech\Code\BioCRNPyler\docs>make.bat HTML
> Running Sphinx v3.4.0
> 
> Sphinx error:
> Builder name HTML not registered or available through entry point

Option A:
try this: C:\Users\wp_ix\OneDrive\Caltech\Code\**BioCRNPyler**>make docs
Option B: 
make html (small case, I've updated the wiki as well, sorry about that)

**Comment by WilliamIX** [comment]
Cool - I got it to work through option B. Option A still doesn't work for some reason....but no problem. Thanks for setting this up. Merge approved.

**Review by WilliamIX — APPROVED** [review]

**Comment by zoltuz** [comment]
> Cool - I got it to work through option B. Option A still doesn't work for some reason....but no problem. Thanks for setting this up. Merge approved.

Thanks for the feedback! I have some plans to shrink the number of commands require down to one in the next PR.

**Pull request merged**
