### PR TITLE
Energy extract models

### LINKED ISSUE #13: Create Mechanisms for Energy Utilization
Ideally these mechanisms should link into transcription and translation mechanisms in some way. TBD how best to do this. It would be nice to have easily interchangeable energy usage mechanisms.

### LINKED ISSUE #31: Port over some existing parameters from Vipul's work
Needs to be in the correct new format (what is that format?)
Test the parameter loading and all the levels --> unit tests!

### PR DESCRIPTION
**Pull request by WilliamIX**
This branch produces an EnergyTxTlExtract with limited fuel resources. This new Extract makes use of a new Component, Metabolite, and a new Mechanisms including OneStepPathway in mechanisms_metabolic.py and Energy_Transcription_MM and Energy_translation_MM. These are collectively used recreate the Model from Vipul's paper with a few minor modifcations to avoid time dependent rates and simplify some of the species. These results are detailed in a new jupyter notebook in the advanced examples folder along with a parameter file that includes rates from Vipul's paper.

Note: This PR is built on top of the initial_concentrations PR.

closes #31 
closes #13

### CODE REVIEW

**Comment by zoltuz** [comment]
Somehow lots of initial concentration-related stuff leached into this PR. Can you remove those unrelate changes? It will be a git challenging, but it is doable, here a guide on how to do so:
https://www.youtube.com/watch?v=ElRzTuYln0M&ab_channel=TheModernCoder

**Comment by ayush9pandey** [comment]
Maybe we just merge initial concentration first then do this one, then those should disappear right?

**Comment by zoltuz** [comment]
> Maybe we just merge initial concentration first then do this one, then those should disappear right?

Good idea! If William rebase/merge this branch with the dev, after #209  gets merged into dev then most of the problems go away. My fear is that there is initial concentration-related stuff in this PR that is **not** in the other PR. (After rebase/merge we will see that)

**Comment by WilliamIX** [comment]
> > Maybe we just merge initial concentration first then do this one, then those should disappear right?
> 
> Good idea! If William rebase/merge this branch with the dev, after #209 gets merged into dev then most of the problems go away. My fear is that there is initial concentration-related stuff in this PR that is **not** in the other PR. (After rebase/merge we will see that)

At the top of the PR I noted it was built on top of the initial conditions PR so I could use those features and not have to rewrite things later.

**Review by zoltuz — APPROVED** [review]
Spot on PR! It was easy to review it, thanks!

**Pull request merged**
