### PR TITLE
Dev to Master Version 1.0.3

### PR DESCRIPTION
**Pull request by WilliamIX**

### CODE REVIEW

**Comment by ayush9pandey** [comment]
Do we go to version 1.1.x or we consider this a minor update still (that is 1.0.2 -> 1.0.3)?

**Comment by zoltuz** [comment]
> Do we go to version 1.1.x or we consider this a minor update still (that is 1.0.2 -> 1.0.3)?

William added 1.0.3 to the setup.py.  There are a lot of changes, but do they break the existing examples?  The list in #248 looks okay to me. I'm okay with 1.0.3.

**Comment by ayush9pandey** [comment]
> William added 1.0.3 to the setup.py. There are a lot of changes, but do they break the existing examples? The list in #248 looks okay to me. I'm okay with 1.0.3.

In addition to examples breaking, I would think about new features added as well. Is there is a set of features that is fully new now and that didn't exist in 1.0.2?

But yeah, I'm surely fine with 1.0.3 as well. I would be most interested in the versioning numbers when we go to 2.0 someday :D Clearly, today is not that day.

**Comment by zoltuz** [comment]
> > William added 1.0.3 to the setup.py. There are a lot of changes, but do they break the existing examples? The list in #248 looks okay to me. I'm okay with 1.0.3.
> 
> In addition to examples breaking, I would think about new features added as well. Is there is a set of features that is fully new now and that didn't exist in 1.0.2?
> 
> But yeah, I'm surely fine with 1.0.3 as well. I would be most interested in the versioning numbers when we go to 2.0 someday :D Clearly, today is not that day.

I lost track of many things in the code with the polymer-monomer universe added to the code, in my mind, we are at version 10 already :D

**Review by zoltuz — APPROVED** [review]

**Comment by WilliamIX** [comment]
I think most of these changes are improvements on features that existed in 1.0.2, but not many new features perse. Happy to call it version 1.1.0 though - we did do a ton of work!

**Comment by zoltuz** [comment]
> I think most of these changes are improvements on features that existed in 1.0.2, but not many new features perse. Happy to call it version 1.1.0 though - we did do a ton of work!

That's true! Andrey's plotting video (#222) alone worth 1.1.0! :)

**Comment by WilliamIX** [comment]
> > I think most of these changes are improvements on features that existed in 1.0.2, but not many new features perse. Happy to call it version 1.1.0 though - we did do a ton of work!
> 
> That's true! Andrey's plotting video (#222) alone worth 1.1.0! :)

1.1.0 it is!

**Review by ayush9pandey — APPROVED** [review]

**Review by zoltuz — DISMISSED** [review]

**Comment by WilliamIX** [comment]
@zoltuz any idea why github pages is stalling?

**Review by zoltuz — APPROVED** [review]

**Pull request merged**
