### PR TITLE
Adding import guards for bioscrape and libroadrunner

### PR DESCRIPTION
**Pull request by zoltuz**
This PR adds checking for import error when bioscrape or libroadrunner aren't installed. Unit tests are also added to test expected behavior.  Thus addressing the issues in #95 and #114

This PR also changes how missing simulator is handled:
```python
R = CRN.simulate_with_bioscrape(timepoints, initial_condition_dict = x0)
# Return R = None when no simulator is found also raise a Warning
      
  
if R:
    plt.sca(ax1)
    plt.plot(R["time"], R[str(protein1)], ":", label = f"protein1 [g1c]={g1c}", color = color)
    plt.plot(R["time"], R[str(protein2)], label = f"protein2 [g1c]={g1c}", color = color)
```

This also means all examples with simulations were refactored, i.e. try-except blocks were removed everywhere.

@WilliamIX please sign off this interface change.

### CODE REVIEW

**Comment by ayush9pandey** [comment]
I like the changes! Not sure what the codecov check fail is all about (didn't look too much into it)

**Comment by zoltuz** [comment]
> I like the changes! Not sure what the codecov check fail is all about (didn't look too much into it)
codecov has two thresholds: absolute threshold (what's the coverage change on all of the code), that passed; and relative threshold (what's the coverage change on the lines affected by this PR), this one failed.  
> 
> Also, we can slowly change all the example notebooks that work better with this change.
I've refactored all of the examples to work with this new structure.

**Comment by WilliamIX** [comment]
@zoltuz for some reason I cannot switch to this PR and look at it locally - I think all the changes look good, but wanted to test them first. Any idea what could be going wrong?

image

**Comment by zoltuz** [comment]
> @zoltuz for some reason I cannot switch to this PR and look at it locally - I think all the changes look good, but wanted to test them first. Any idea what could be going wrong?
> 
> image

Good question! This what I've found: https://stackoverflow.com/questions/52022623/cannot-clone-repo-fatal-remote-did-not-send-all-necessary-objects

I've tried on a freshly cloned repo and it worked for me:
Screenshot 2020-07-07 at 11 24 44

Maybe you need to update your git? 
ps: I've used github CLI: https://cli.github.com/

**Comment by WilliamIX** [comment]
Runs on my computer now (had to reclone biocrnpyler...weird). Merging with Squash just to try it.

**Pull request merged**
