### PR TITLE
Minor SBML writing bug fix

### PR DESCRIPTION
**Pull request by ayush9pandey**
- added the required model ID when creating SBML model
- added name attribute as well to model and compartment when creating SBML model

### CODE REVIEW

**Comment by zoltuz** [comment]
Screenshot 2020-06-26 at 11 07 57
There's a test which checks the content of the SBML file, which needs adjustment. (I guess the model ID is missing)

**Comment by zoltuz** [comment]
btw, you do want this PR to be merged into master directly?

**Comment by ayush9pandey** [comment]
Yeah,  I am looking into this, not sure how to fix this error.

**Comment by ayush9pandey** [comment]
> 
> 
> btw, you do want this PR to be merged into master directly?

Yes, that would be helpful for the bootcamp (the overall changes are only in a couple lines). I didn't change the version number in order to avoid conflicts. 

Please excuse this negligence of the contribution rules.

**Comment by ayush9pandey** [comment]
The source of the error is the following: I have added a random number to create a model ID. This random number changes every time and so test fails because it doesn't get the exact id in the SBML string. 

Suggestions on better ways to create a model ID that is not always the same for every model that is written out?

**Comment by zoltuz** [comment]
> The source of the error is the following: I have added a random number to create a model ID. This random number changes every time and so test fails because it doesn't get the exact id in the SBML string.
> 
> Suggestions on better ways to create a model ID that is not always the same for every model that is written out?

How about generating that random number when you compile the CRN and saving it inside the CRN instance 
self._network_id =rand()

**Comment by zoltuz** [comment]
> > btw, you do want this PR to be merged into master directly?
> 
> Yes, that would be helpful for the bootcamp (the overall changes are only in a couple lines). I didn't change the version number in order to avoid conflicts.
> 
> Please excuse this negligence of the contribution rules.

I see, no worries!

**Comment by ayush9pandey** [comment]
> 
> 
> > The source of the error is the following: I have added a random number to create a model ID. This random number changes every time and so test fails because it doesn't get the exact id in the SBML string.
> > Suggestions on better ways to create a model ID that is not always the same for every model that is written out?
> 
> How about generating that random number when you compile the CRN and saving it inside the CRN instance
> self._network_id =rand()

I tried a different fix: Added an optional argument called `model_id` when creating SBML model so the model ID can be fixed to a desired name if needed. Changed the test code to have a fixed ID

**Comment by ayush9pandey** [comment]
All green :) @zoltuz  can we merge now?

**Comment by zoltuz** [comment]
> All green :) @zoltuz can we merge now?

Looks good! We can future proof it a bit better next time.

**Comment by zoltuz** [comment]
Please merge these changes into the dev branch as well. Thanks!

**Comment by ayush9pandey** [comment]
> Looks good! We can future proof it a bit better next time by extracting the model_id string as a constant.
Yeah, that would be better.

> Please merge these changes into the dev branch as well. Thanks!
Yes, will do. Should I create another PR for that?

**Pull request merged**
